stages:
  - build
 
build-job:
  stage: build
  only:
    - one_main_file
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind

  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""

  before_script:
    - sleep 15
    - docker login $DOCKER_REGISTRY -u $DOCKER_USER -p $DOCKER_PASS
    - apk update
    - apk add jq
  script:
    - docker build -t $DOCKER_REGISTRY/test/deploy:v1.0.0 -t $DOCKER_REGISTRY/test/deploy:latest .
    - docker push $DOCKER_REGISTRY/test/deploy:v1.0.0
    - docker push $DOCKER_REGISTRY/test/deploy:latest
